name: packers_bility
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_otp_text_field: ^1.1.1
  easy_localization: ^3.0.1
  carousel_slider: ^4.2.1

  responsive_grid_list: ^1.3.1
  ff_navigation_bar: ^0.0.1
  curved_navigation_bar: ^1.0.3
  fancy_bottom_navigation: ^0.3.2
  firebase_auth: ^4.4.0
  # flutter_svg: ^2.0.4

  google_fonts: 
  firebase_core: ^2.8.0
  font_awesome_flutter: ^10.4.0
  google_sign_in: ^6.0.2
  dio: ^5.0.3
  connectivity_plus: ^3.0.3
  fluttertoast: ^8.2.1
  equatable: ^0.1.6
  flutter_bloc: 
  flutter_svg: ^1.1.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/translations/